on:
  workflow_dispatch:
    inputs:
     
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
      services:
        description: 'services to be build'
        type: choice
        required: true
        options:
          - vis
          - vish

jobs:
## Building services
  visbuild:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: step1 - checkout from master branch
      - uses: actions/checkout@v2
      
      - name: step2- setup JDK 1.8
      - uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      
      - name: step- 3 Build maven project
        run: mvn -B install --file vis/pom.xml
 
  vishbuild: 
    runs-on: [ ubuntu-latest ]
    steps:
      - name: step1 - checkout from mster branch
      - uses: actions/checkout@v2
      
      - name: step2- setup JDK 1.8
      - uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      
      - name: step- 3 Build maven project
        run: mvn -B package --file vish/pom.xml
  
## Deploy to environments
 

  
  
