on:
  workflow_dispatch:
    inputs:
     
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
      services:
        description: 'services to be build'
        type: boolean
        required: true
        options:
          - vis
          - vish

jobs:
  visbuild:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: step1 - checkout from mster branch
      - uses: actions/checkout@v2
      
      - name: step2- setup JDK 1.8
      - uses: actions/setup-java@v1
      
      - name: step- 3 Build maven project
        run: mvn -B package --file vis/pom.xml
      
  
